spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: com.dominikyang.lastdance.dubbo.provider.service.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://47.93.245.153:8848